services:
  back-end:
    build:
      context: ./
      dockerfile: Dockerfile
      target: exec
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/church
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=church
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - db-app:/var/lib/postgresql/data

volumes:
  db-app: