CREATE TABLE tb_user(
    id BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role_id BIGINT UNIQUE NOT NULL,
    FOREIGN KEY (role_id) REFERENCES tb_role(id)
);